# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'documentos_documentos_de_pecas_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_peca01(object):
    def setupUi(self, peca01):
        peca01.setObjectName("peca01")
        peca01.resize(1290, 841)
        peca01.setMinimumSize(QtCore.QSize(1290, 841))
        peca01.setMaximumSize(QtCore.QSize(1290, 841))
        peca01.setStyleSheet("background-color: rgb(255, 255, 255);")
        peca01.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(peca01)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(220, 15, 821, 71))
        self.label_titulo.setMinimumSize(QtCore.QSize(0, 0))
        self.label_titulo.setStyleSheet("\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 30pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(155, 228, 179);\n"
"\n"
"")
        self.label_titulo.setScaledContents(False)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setWordWrap(False)
        self.label_titulo.setIndent(-1)
        self.label_titulo.setObjectName("label_titulo")
        self.botao_home = QtWidgets.QPushButton(self.centralwidget)
        self.botao_home.setGeometry(QtCore.QRect(20, 10, 91, 91))
        self.botao_home.setStyleSheet("\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.botao_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Home.Documentos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon)
        self.botao_home.setIconSize(QtCore.QSize(75, 75))
        self.botao_home.setObjectName("botao_home")
        self.label_imagem = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem.setGeometry(QtCore.QRect(230, 90, 1091, 661))
        self.label_imagem.setText("")
        self.label_imagem.setPixmap(QtGui.QPixmap("imagens/Perfil_45_2.png"))
        self.label_imagem.setObjectName("label_imagem")
        self.botao_seta = QtWidgets.QPushButton(self.centralwidget)
        self.botao_seta.setGeometry(QtCore.QRect(1110, 10, 101, 81))
        self.botao_seta.setStyleSheet("\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.botao_seta.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Seta Preta para direita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_seta.setIcon(icon1)
        self.botao_seta.setIconSize(QtCore.QSize(65, 65))
        self.botao_seta.setObjectName("botao_seta")
        peca01.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(peca01)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        peca01.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(peca01)
        self.statusbar.setObjectName("statusbar")
        peca01.setStatusBar(self.statusbar)

        self.retranslateUi(peca01)
        QtCore.QMetaObject.connectSlotsByName(peca01)

    def retranslateUi(self, peca01):
        _translate = QtCore.QCoreApplication.translate
        peca01.setWindowTitle(_translate("peca01", "MainWindow"))
        self.label_titulo.setText(_translate("peca01", "PERFIL DE ALUMÍNIO DE 30x30"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    peca01 = QtWidgets.QMainWindow()
    ui = Ui_peca01()
    ui.setupUi(peca01)
    peca01.show()
    sys.exit(app.exec_())
