# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Feliz_aniversario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Feliz_aniversario(object):
    def setupUi(self, Feliz_aniversario):
        Feliz_aniversario.setObjectName("Feliz_aniversario")
        Feliz_aniversario.resize(1290, 841)
        Feliz_aniversario.setMinimumSize(QtCore.QSize(1290, 841))
        Feliz_aniversario.setMaximumSize(QtCore.QSize(1290, 841))
        Feliz_aniversario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Feliz_aniversario)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("../../Downloads/Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.botao_obrigado = QtWidgets.QPushButton(self.centralwidget)
        self.botao_obrigado.setGeometry(QtCore.QRect(460, 620, 441, 141))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_obrigado.setFont(font)
        self.botao_obrigado.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(234, 229, 239);\n"
"border-width:0px;\n"
"\n"
"border-radius: 30px;")
        self.botao_obrigado.setObjectName("botao_obrigado")
        self.label_patinho = QtWidgets.QLabel(self.centralwidget)
        self.label_patinho.setGeometry(QtCore.QRect(870, 330, 211, 231))
        self.label_patinho.setStyleSheet("background-color: rgb(234, 229, 239);")
        self.label_patinho.setText("")
        self.label_patinho.setScaledContents(False)
        self.label_patinho.setObjectName("label_patinho")
        self.label_texto = QtWidgets.QLabel(self.centralwidget)
        self.label_texto.setGeometry(QtCore.QRect(40, 300, 691, 291))
        self.label_texto.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"font: 75 18pt \"Bosch Sans Bold\";\n"
"border-radius: 30px;")
        self.label_texto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_texto.setObjectName("label_texto")
        self.label_feliz_aniversario = QtWidgets.QLabel(self.centralwidget)
        self.label_feliz_aniversario.setGeometry(QtCore.QRect(820, 30, 431, 161))
        self.label_feliz_aniversario.setText("")
        self.label_feliz_aniversario.setPixmap(QtGui.QPixmap("imagens/Feliz_aniversario.png"))
        self.label_feliz_aniversario.setScaledContents(True)
        self.label_feliz_aniversario.setObjectName("label_feliz_aniversario")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(20, 30, 171, 141))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("imagens/Logo_Access_control_simples.png"))
        self.label_logo.setObjectName("label_logo")
        self.label_access_control = QtWidgets.QLabel(self.centralwidget)
        self.label_access_control.setGeometry(QtCore.QRect(210, 80, 351, 41))
        self.label_access_control.setText("")
        self.label_access_control.setPixmap(QtGui.QPixmap("imagens/Access_control.png"))
        self.label_access_control.setObjectName("label_access_control")
        self.label_gif = QtWidgets.QLabel(self.centralwidget)
        self.label_gif.setGeometry(QtCore.QRect(20, 10, 601, 751))
        self.label_gif.setText("")
        self.label_gif.setObjectName("label_gif")
        self.label_gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_gif_2.setGeometry(QtCore.QRect(650, 0, 591, 741))
        self.label_gif_2.setText("")
        self.label_gif_2.setObjectName("label_gif_2")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(40, 210, 721, 71))
        self.label_nome.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"font: 75 20pt \"Bosch Sans Bold\";\n"
"border-radius: 30px;")
        self.label_nome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_nome.setObjectName("label_nome")
        self.label_gif_2.raise_()
        self.label_gif.raise_()
        self.Label_Borda.raise_()
        self.botao_obrigado.raise_()
        self.label_patinho.raise_()
        self.label_texto.raise_()
        self.label_feliz_aniversario.raise_()
        self.label_logo.raise_()
        self.label_access_control.raise_()
        self.label_nome.raise_()
        Feliz_aniversario.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Feliz_aniversario)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Feliz_aniversario.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Feliz_aniversario)
        self.statusbar.setObjectName("statusbar")
        Feliz_aniversario.setStatusBar(self.statusbar)

        self.retranslateUi(Feliz_aniversario)
        QtCore.QMetaObject.connectSlotsByName(Feliz_aniversario)

    def retranslateUi(self, Feliz_aniversario):
        _translate = QtCore.QCoreApplication.translate
        Feliz_aniversario.setWindowTitle(_translate("Feliz_aniversario", "MainWindow"))
        self.botao_obrigado.setText(_translate("Feliz_aniversario", "OBRIGADO!!"))
        self.label_texto.setText(_translate("Feliz_aniversario", "Você pensava que a gente ia esquecer seu dia,\n"
"que iríamos permitir que ele passasse em branco.\n"
"Jamais!\n"
"\n"
"É um privilégio contar com seu profissionalismo \n"
"e caráter todos os dias, por isso agradecemos\n"
"profundamente seu esforço.\n"
"Parabéns por mais um ano de vida, sucesso!\n"
""))
        self.label_nome.setText(_translate("Feliz_aniversario", "Fulano"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Feliz_aniversario = QtWidgets.QMainWindow()
    ui = Ui_Feliz_aniversario()
    ui.setupUi(Feliz_aniversario)
    Feliz_aniversario.show()
    sys.exit(app.exec_())
