# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Manutencao.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manutencao(object):
    def setupUi(self, Manutencao):
        Manutencao.setObjectName("Manutencao")
        Manutencao.resize(1290, 841)
        Manutencao.setMinimumSize(QtCore.QSize(1290, 841))
        Manutencao.setMaximumSize(QtCore.QSize(1290, 841))
        Manutencao.setStyleSheet("background-color: rgb(255, 255, 255);")
        Manutencao.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Manutencao)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 10, 1251, 761))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_fundo.setFont(font)
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"border-radius: 0px;\n"
"background-color: rgb(208, 212, 216);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.botao_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cancelar.setGeometry(QtCore.QRect(1100, 10, 171, 171))
        self.botao_cancelar.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 34pt \"Bosch Sans Bold\";\n"
"background-color: rgb(255,207,0);")
        self.botao_cancelar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/home_preto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_cancelar.setIcon(icon)
        self.botao_cancelar.setIconSize(QtCore.QSize(130, 130))
        self.botao_cancelar.setObjectName("botao_cancelar")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(20, 10, 1251, 171))
        self.label_titulo.setStyleSheet("font: 75 52pt \"Bosch Sans Bold\";\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"background-color: rgb(255,207,0);")
        self.label_titulo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 208, 581, 531))
        self.label_2.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 90px;\n"
"\n"
"font: 75 34pt \"Bosch Sans Bold\";\n"
"background-color: rgb(138, 144, 151);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 400, 261, 281))
        self.label_4.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 34pt \"Bosch Sans Bold\";\n"
"background-color: rgb(255,207,0);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("imagens/Raio.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1080, 280, 141, 151))
        self.pushButton.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Touch_painel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(120, 120))
        self.pushButton.setObjectName("pushButton")
        self.label_liberar_trava_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_liberar_trava_2.setGeometry(QtCore.QRect(100, 245, 481, 81))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_liberar_trava_2.setFont(font)
        self.label_liberar_trava_2.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"\n"
"border-radius: 90px;\n"
"\n"
"font: 75 40pt \"Bosch Sans Bold\";\n"
"background-color: rgb(138, 144, 151);")
        self.label_liberar_trava_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_liberar_trava_2.setObjectName("label_liberar_trava_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 480, 91, 61))
        self.label_5.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 0px;\n"
"\n"
"font: 75 34pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0, 0, 0);")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 500, 91, 21))
        self.label_6.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 0px;\n"
"\n"
"font: 75 34pt \"Bosch Sans Bold\";\n"
"background-color: rgb(237, 0, 7);")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 465, 51, 91))
        self.label_7.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 20px;\n"
"\n"
"font: 75 34pt \"Bosch Sans Bold\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_liberar_trava_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_liberar_trava_3.setGeometry(QtCore.QRect(700, 40, 361, 111))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_liberar_trava_3.setFont(font)
        self.label_liberar_trava_3.setStyleSheet("font: 75 52pt \"Bosch Sans Bold\";\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255,207,0);")
        self.label_liberar_trava_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_liberar_trava_3.setObjectName("label_liberar_trava_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(665, 280, 421, 151))
        self.pushButton_2.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 0px;\n"
"\n"
"font: 75 24pt \"Bosch Sans Bold\";\n"
"background-color: rgb(155, 228, 179);")
        self.pushButton_2.setIconSize(QtCore.QSize(120, 120))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1080, 510, 141, 151))
        self.pushButton_3.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagens/Raio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(125, 125))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(665, 510, 421, 151))
        self.pushButton_4.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 0px;\n"
"\n"
"font: 75 24pt \"Bosch Sans Bold\";\n"
"background-color: rgb(155, 228, 179);")
        self.pushButton_4.setIconSize(QtCore.QSize(120, 120))
        self.pushButton_4.setObjectName("pushButton_4")
        self.Label_Borda.raise_()
        self.label_fundo.raise_()
        self.label_titulo.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.botao_cancelar.raise_()
        self.pushButton.raise_()
        self.label_liberar_trava_2.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_liberar_trava_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        Manutencao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Manutencao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Manutencao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Manutencao)
        self.statusbar.setObjectName("statusbar")
        Manutencao.setStatusBar(self.statusbar)

        self.retranslateUi(Manutencao)
        QtCore.QMetaObject.connectSlotsByName(Manutencao)

    def retranslateUi(self, Manutencao):
        _translate = QtCore.QCoreApplication.translate
        Manutencao.setWindowTitle(_translate("Manutencao", "MainWindow"))
        self.botao_cancelar.setWhatsThis(_translate("Manutencao", "<html><head/><body><p><span style=\" color:#ffffff;\">OI</span></p></body></html>"))
        self.label_titulo.setText(_translate("Manutencao", "MANUTENÇÃO"))
        self.label_liberar_trava_2.setText(_translate("Manutencao", "PAINEL ELÉTRICO"))
        self.label_liberar_trava_3.setText(_translate("Manutencao", "AJUSTES"))
        self.pushButton_2.setText(_translate("Manutencao", "LIBERAR TRAVA DO\n"
"PAINEL ELÉTRICO"))
        self.pushButton_4.setText(_translate("Manutencao", "ENERGIZAR CONTATOR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Manutencao = QtWidgets.QMainWindow()
    ui = Ui_Manutencao()
    ui.setupUi(Manutencao)
    Manutencao.show()
    sys.exit(app.exec_())
