# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu01_limitado.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu01_limitado(object):
    def setupUi(self, Menu01_limitado):
        Menu01_limitado.setObjectName("Menu01_limitado")
        Menu01_limitado.resize(1290, 841)
        Menu01_limitado.setMinimumSize(QtCore.QSize(1275, 841))
        Menu01_limitado.setMaximumSize(QtCore.QSize(1290, 841))
        Menu01_limitado.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Menu01_limitado)
        self.centralwidget.setObjectName("centralwidget")
        self.Botao_Documentos = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Documentos.setGeometry(QtCore.QRect(672, 270, 240, 240))
        self.Botao_Documentos.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: inside;\n"
"font: 75 9pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0, 150, 232);\n"
"color: rgb(255, 207, 0);\n"
"}")
        self.Botao_Documentos.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("S:/PM/ter/ets/Inter_Setor/COMPARTILHADO/PROJETOS/Mecatrônica_2_Turma/Grupo_4/5_PROGRAMAÇÃO/CODIGO/Jaburu/imagens/DOCUMENTOS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Documentos.setIcon(icon)
        self.Botao_Documentos.setIconSize(QtCore.QSize(220, 220))
        self.Botao_Documentos.setObjectName("Botao_Documentos")
        self.Botao_Liberar_Maquina = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Liberar_Maquina.setGeometry(QtCore.QRect(63, 270, 240, 240))
        self.Botao_Liberar_Maquina.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: inside;\n"
"font: 75 9pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0, 136, 74);\n"
"color: rgb(255, 207, 0);\n"
"}")
        self.Botao_Liberar_Maquina.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("S:/PM/ter/ets/Inter_Setor/COMPARTILHADO/PROJETOS/Mecatrônica_2_Turma/Grupo_4/5_PROGRAMAÇÃO/CODIGO/Jaburu/imagens/CADEADO_FECHADO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Liberar_Maquina.setIcon(icon1)
        self.Botao_Liberar_Maquina.setIconSize(QtCore.QSize(220, 220))
        self.Botao_Liberar_Maquina.setObjectName("Botao_Liberar_Maquina")
        self.Botao_Interface_Didatica = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Interface_Didatica.setGeometry(QtCore.QRect(365, 270, 240, 240))
        self.Botao_Interface_Didatica.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: inside;\n"
"font: 75 9pt \"Bosch Sans Bold\";\n"
"background-color: rgb(213, 67, 203);\n"
"color: rgb(255, 207, 0);\n"
"}")
        self.Botao_Interface_Didatica.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("S:/PM/ter/ets/Inter_Setor/COMPARTILHADO/PROJETOS/Mecatrônica_2_Turma/Grupo_4/5_PROGRAMAÇÃO/CODIGO/Jaburu/imagens/INTERFACE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Interface_Didatica.setIcon(icon2)
        self.Botao_Interface_Didatica.setIconSize(QtCore.QSize(220, 220))
        self.Botao_Interface_Didatica.setObjectName("Botao_Interface_Didatica")
        self.Botao_Registros = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Registros.setGeometry(QtCore.QRect(980, 270, 240, 240))
        self.Botao_Registros.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: inside;\n"
"font: 75 9pt \"Bosch Sans Bold\";\n"
"background-color: rgb(237, 0, 7);\n"
"color: rgb(255, 207, 0);\n"
"}")
        self.Botao_Registros.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("S:/PM/ter/ets/Inter_Setor/COMPARTILHADO/PROJETOS/Mecatrônica_2_Turma/Grupo_4/5_PROGRAMAÇÃO/CODIGO/Jaburu/imagens/REGISTROS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Registros.setIcon(icon3)
        self.Botao_Registros.setIconSize(QtCore.QSize(220, 220))
        self.Botao_Registros.setObjectName("Botao_Registros")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("S:/PM/ter/ets/Inter_Setor/COMPARTILHADO/PROJETOS/Mecatrônica_2_Turma/Grupo_4/5_PROGRAMAÇÃO/CODIGO/Jaburu/Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.Label_Menu_De_Usuario = QtWidgets.QLabel(self.centralwidget)
        self.Label_Menu_De_Usuario.setGeometry(QtCore.QRect(150, 60, 875, 121))
        self.Label_Menu_De_Usuario.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 65pt \"Bosch Sans Bold\";")
        self.Label_Menu_De_Usuario.setObjectName("Label_Menu_De_Usuario")
        self.Label_Colaborador = QtWidgets.QLabel(self.centralwidget)
        self.Label_Colaborador.setGeometry(QtCore.QRect(60, 650, 591, 41))
        self.Label_Colaborador.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 15pt \"Bosch Sans Bold\";")
        self.Label_Colaborador.setObjectName("Label_Colaborador")
        self.Label_EDV = QtWidgets.QLabel(self.centralwidget)
        self.Label_EDV.setGeometry(QtCore.QRect(60, 700, 371, 41))
        self.Label_EDV.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 15pt \"Bosch Sans Bold\";")
        self.Label_EDV.setObjectName("Label_EDV")
        self.Botao_Sair = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Sair.setGeometry(QtCore.QRect(1080, 30, 161, 161))
        self.Botao_Sair.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: inside;\n"
"font: 75 9pt \"Bosch Sans Bold\";\n"
"background-color: rgb(139, 34, 132);\n"
"color: rgb(255, 207, 0);\n"
"}")
        self.Botao_Sair.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("S:/PM/ter/ets/Inter_Setor/COMPARTILHADO/PROJETOS/Mecatrônica_2_Turma/Grupo_4/5_PROGRAMAÇÃO/CODIGO/Jaburu/imagens/SAIR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Sair.setIcon(icon4)
        self.Botao_Sair.setIconSize(QtCore.QSize(140, 140))
        self.Botao_Sair.setObjectName("Botao_Sair")
        Menu01_limitado.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu01_limitado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Menu01_limitado.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu01_limitado)
        self.statusbar.setObjectName("statusbar")
        Menu01_limitado.setStatusBar(self.statusbar)

        self.retranslateUi(Menu01_limitado)
        QtCore.QMetaObject.connectSlotsByName(Menu01_limitado)

    def retranslateUi(self, Menu01_limitado):
        _translate = QtCore.QCoreApplication.translate
        Menu01_limitado.setWindowTitle(_translate("Menu01_limitado", "MainWindow"))
        self.Botao_Liberar_Maquina.setWhatsThis(_translate("Menu01_limitado", "<html><head/><body><p><br/></p></body></html>"))
        self.Label_Menu_De_Usuario.setText(_translate("Menu01_limitado", "MENU DE USUÁRIO"))
        self.Label_Colaborador.setText(_translate("Menu01_limitado", "COLABORADOR:"))
        self.Label_EDV.setText(_translate("Menu01_limitado", "EDV:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu01_limitado = QtWidgets.QMainWindow()
    ui = Ui_Menu01_limitado()
    ui.setupUi(Menu01_limitado)
    Menu01_limitado.show()
    sys.exit(app.exec_())
